[package]
name = "bindings-ts"
version = "0.3.0"
authors = ["Ambuda <ambuda.library@gmail.com>", "Ronit<ronit@siva.sh>"]
description = "Universal WebAssembly and TypeScript bindings for Vidyut"
keywords = ["vidyut", "sanskrit", "transliteration", "sandhi", "chanda", "vyakarana"]
license = "MIT"
repository = "https://github.com/sivashaktift/vidyut"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.4"
vidyut-chandas = { path = "../vidyut-chandas", default-features = false }
vidyut-lipi = { path = "../vidyut-lipi", default-features = false }
vidyut-prakriya = { path = "../vidyut-prakriya" }
vidyut-sandhi = { path = "../vidyut-sandhi", default-features = false }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development but requires
# all the `std::fmt` and `std::panicking` infrastructure, so it isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
